import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import Image from 'next/image'
import { sanityClient, urlFor } from "../sanity"
import { PostTypeInterface } from "../typings"
import Link from 'next/link'

interface Props {
  posts: [PostTypeInterface]
}

export default function Home({ posts }: Props) {
  console.log(posts)
  return (
    <div className="max-w-7xl mx-auto" >
      <Head>
        <title>Medium Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      {/* Banner */}
      <div className='flex items-center justify-between bg-yellow-400 border-y border-black py-10 lg:py-0'>
        <div className="px-10 space-y-5">
          <h1 className='text-6xl max-w-xl font-serif'><span className='underline decoration-black decoration-4'>Medium</span> is a place to write, and connect</h1>
          <h2 className=''>It&apos;s easy and free to post your thinking on any topic and connect with millons of readers.</h2>
        </div>
        <img className='hidden md:inline-flex h-32 lg:h-full' src="https://iconape.com/wp-content/png_logo_vector/medium-m.png" alt="" />
      </div>

      {/* Posts */}

      <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 md:gap-6 p-2 lg:p-6'>
        {posts.map((post) => {
          return (
            <Link key={post._id} href={`/post/${post.slug.current}`}>
              <div className=''>
                <img src={urlFor(post.mainImage).url()} alt={post.title} />
                <div className='flex justify-between p-5 bg-white'>
                  <div>
                    <p>{post.title}</p>
                    <p>
                      {post.description} by {post.author.name}
                    </p>
                  </div>
                  <img className='h-12 w-12 rounded-full' src={urlFor(post.author.image).url()} alt={post.author.name} />
                </div>
              </div>
            </Link>
          )
        })}

      </div>
    </div>
  )
}

export const getServerSideProps = async (params: Props) => {
  const query = `*[_type == "post"] {
    _id,
    title,
    author -> {
      name,
      image
      }, 
    description,
    mainImage,
    slug
    }`;
  const posts = await sanityClient.fetch(query);

  return {
    props: {
      posts,
    }
  }
}